/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sistemamusicapresentacion.albumes;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import sistemamusica.dtos.AlbumDTO;
import sistemamusica.dtos.CancionDTO;
import sistemamusica.dtos.UsuarioDTO;
import sistemamusicanegocio.exception.NegocioException;
import sistemamusicanegocio.fabrica.FabricaObjetosNegocio;
import sistemamusicanegocio.interfaces.IAlbumesBO;
import sistemamusicapresentacion.main.ControladorUniversal;

/**
 *
 * @author gael_
 */
public class frmAgregarCancionesAlbum extends javax.swing.JFrame {

    private final IAlbumesBO albumesBO = FabricaObjetosNegocio.crearAlbumesBO();
    UsuarioDTO usuario;
    ControladorUniversal controlador;
    AlbumDTO albumRecibido;
    private List<CancionDTO> cancionesAgregar = new ArrayList<>();

    /**
     * Creates new form frmAgregarCancionesAlbum
     *
     * @param controlador Controlador
     * @param usuario Usuario
     * @param album Album
     */
    public frmAgregarCancionesAlbum(ControladorUniversal controlador, UsuarioDTO usuario, AlbumDTO album) {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Agregar Cancion Album");
        this.albumRecibido = album;
        this.usuario = usuario;
        this.controlador = controlador;
    }

    /**
     * Metodo para facilitar la lectura de la operacion realizada
     *
     * @param cancion Cancion a enlistar
     */
    private void enlistarCancion(CancionDTO cancion) {
        this.cancionesAgregar.add(cancion);
    }

    /**
     * Metodo para facilitar la lectura de la operacion realizada
     */
    private void limpiarCampos() {
        txtNombreCancion.setText("");
        txtDuracion.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelFondo2 = new javax.swing.JPanel();
        panelVerde2 = new javax.swing.JPanel();
        btnArtistas2 = new javax.swing.JButton();
        labelArtistas = new javax.swing.JLabel();
        labelAlbumes = new javax.swing.JLabel();
        btnAlbumes = new javax.swing.JButton();
        btnCanciones = new javax.swing.JButton();
        labelCanciones = new javax.swing.JLabel();
        labelUsuario = new javax.swing.JLabel();
        btnUsuario = new javax.swing.JButton();
        labelMusicio1 = new javax.swing.JLabel();
        textoAgregarCancion = new javax.swing.JLabel();
        btnTerminar = new javax.swing.JButton();
        btnAgregarCancionAlbum = new javax.swing.JButton();
        labelNombreCancin = new javax.swing.JLabel();
        txtNombreCancion = new javax.swing.JTextField();
        labelDuracion = new javax.swing.JLabel();
        txtDuracion = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelFondo2.setBackground(new java.awt.Color(0, 0, 0));

        panelVerde2.setBackground(new java.awt.Color(30, 215, 96));

        btnArtistas2.setBackground(new java.awt.Color(30, 215, 96));
        btnArtistas2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BlackStar.png"))); // NOI18N
        btnArtistas2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnArtistas2ActionPerformed(evt);
            }
        });

        labelArtistas.setFont(new java.awt.Font("Gotham Black", 0, 12)); // NOI18N
        labelArtistas.setText("Artistas");

        labelAlbumes.setFont(new java.awt.Font("Gotham Black", 0, 12)); // NOI18N
        labelAlbumes.setText("Albumes");

        btnAlbumes.setBackground(new java.awt.Color(30, 215, 96));
        btnAlbumes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/musica.png"))); // NOI18N

        btnCanciones.setBackground(new java.awt.Color(30, 215, 96));
        btnCanciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/disco.png"))); // NOI18N
        btnCanciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancionesActionPerformed(evt);
            }
        });

        labelCanciones.setFont(new java.awt.Font("Gotham Black", 0, 12)); // NOI18N
        labelCanciones.setText("Canciones");

        labelUsuario.setFont(new java.awt.Font("Gotham Black", 0, 12)); // NOI18N
        labelUsuario.setText("Usuario");

        btnUsuario.setBackground(new java.awt.Color(30, 215, 96));
        btnUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/usuario.png"))); // NOI18N
        btnUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelVerde2Layout = new javax.swing.GroupLayout(panelVerde2);
        panelVerde2.setLayout(panelVerde2Layout);
        panelVerde2Layout.setHorizontalGroup(
            panelVerde2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelVerde2Layout.createSequentialGroup()
                .addGroup(panelVerde2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelVerde2Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(panelVerde2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelCanciones)
                            .addGroup(panelVerde2Layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addGroup(panelVerde2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelAlbumes)
                                    .addGroup(panelVerde2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(btnCanciones)
                                        .addComponent(btnAlbumes)
                                        .addComponent(btnArtistas2))
                                    .addComponent(labelArtistas)))))
                    .addGroup(panelVerde2Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(panelVerde2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelUsuario)
                            .addComponent(btnUsuario))))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        panelVerde2Layout.setVerticalGroup(
            panelVerde2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelVerde2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(btnArtistas2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelArtistas, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(btnAlbumes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelAlbumes, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCanciones)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelCanciones, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 144, Short.MAX_VALUE)
                .addComponent(btnUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );

        labelMusicio1.setFont(new java.awt.Font("Gotham Black", 1, 36)); // NOI18N
        labelMusicio1.setForeground(new java.awt.Color(30, 215, 96));
        labelMusicio1.setText("Music.io");

        textoAgregarCancion.setFont(new java.awt.Font("Gotham Black", 1, 36)); // NOI18N
        textoAgregarCancion.setForeground(new java.awt.Color(30, 215, 96));
        textoAgregarCancion.setText("Agregar Canciones");

        btnTerminar.setBackground(new java.awt.Color(30, 215, 96));
        btnTerminar.setFont(new java.awt.Font("Gotham Black", 1, 18)); // NOI18N
        btnTerminar.setText("Terminar");
        btnTerminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTerminarActionPerformed(evt);
            }
        });

        btnAgregarCancionAlbum.setBackground(new java.awt.Color(30, 215, 96));
        btnAgregarCancionAlbum.setFont(new java.awt.Font("Gotham Black", 1, 18)); // NOI18N
        btnAgregarCancionAlbum.setText("Agregar Cancion");
        btnAgregarCancionAlbum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarCancionAlbumActionPerformed(evt);
            }
        });

        labelNombreCancin.setFont(new java.awt.Font("Gotham Bold", 1, 14)); // NOI18N
        labelNombreCancin.setForeground(new java.awt.Color(30, 215, 96));
        labelNombreCancin.setText("nombre de la cancion:");

        labelDuracion.setFont(new java.awt.Font("Gotham Bold", 1, 14)); // NOI18N
        labelDuracion.setForeground(new java.awt.Color(30, 215, 96));
        labelDuracion.setText("duracion:");

        javax.swing.GroupLayout panelFondo2Layout = new javax.swing.GroupLayout(panelFondo2);
        panelFondo2.setLayout(panelFondo2Layout);
        panelFondo2Layout.setHorizontalGroup(
            panelFondo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFondo2Layout.createSequentialGroup()
                .addComponent(panelVerde2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(panelFondo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFondo2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 141, Short.MAX_VALUE)
                        .addComponent(textoAgregarCancion, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelMusicio1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24))
                    .addGroup(panelFondo2Layout.createSequentialGroup()
                        .addGap(262, 262, 262)
                        .addGroup(panelFondo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNombreCancion, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelNombreCancin)
                            .addComponent(labelDuracion)
                            .addComponent(txtDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAgregarCancionAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnTerminar, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        panelFondo2Layout.setVerticalGroup(
            panelFondo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelVerde2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelFondo2Layout.createSequentialGroup()
                .addGroup(panelFondo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelMusicio1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelFondo2Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(textoAgregarCancion, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(labelNombreCancin)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNombreCancion, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(labelDuracion)
                        .addGap(18, 18, 18)
                        .addComponent(txtDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addComponent(btnAgregarCancionAlbum)
                        .addGap(38, 38, 38)
                        .addComponent(btnTerminar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFondo2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFondo2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnArtistas2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnArtistas2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnArtistas2ActionPerformed

    private void btnCancionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancionesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancionesActionPerformed

    private void btnUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUsuarioActionPerformed

    private void btnTerminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTerminarActionPerformed

        try {
            AlbumDTO albumAgregar = new AlbumDTO(
                    albumRecibido.getNombre(),
                    albumRecibido.getFechaLanzamiento(),
                    albumRecibido.getGenero(),
                    albumRecibido.getImagenPortada(),
                    albumRecibido.getIdArtista(),
                    cancionesAgregar
            );

            AlbumDTO albumObtenido = albumesBO.agregarAlbum(albumAgregar);

            if (albumObtenido != null) {
                System.out.println("Album Obtenido: " + albumObtenido.toString());
            }

            JOptionPane.showMessageDialog(this, "Album agregado exitosamente.", "Info.",
                    JOptionPane.INFORMATION_MESSAGE);

            controlador.mostrarAlbumesPrincipal(usuario);
            this.dispose();
        } catch (NegocioException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Info.",
                    JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnTerminarActionPerformed

    private void btnAgregarCancionAlbumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarCancionAlbumActionPerformed
        String nombreCancion = txtNombreCancion.getText();
        float duracionCancion = Float.parseFloat(txtDuracion.getText());
        String idArtistaObtenido = albumRecibido.getIdArtista();

        try {
            CancionDTO cancionEnlistar = new CancionDTO();
            cancionEnlistar.setTitulo(nombreCancion);
            cancionEnlistar.setDuracion(duracionCancion);
            cancionEnlistar.setIdArtista(idArtistaObtenido);

            enlistarCancion(cancionEnlistar);

            limpiarCampos();
            
            JOptionPane.showMessageDialog(this, "Cancion agregada correctamente",
                    "Info", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al agregar la cancion: " +
                    e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAgregarCancionAlbumActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarCancionAlbum;
    private javax.swing.JButton btnAlbumes;
    private javax.swing.JButton btnArtistas2;
    private javax.swing.JButton btnCanciones;
    private javax.swing.JButton btnTerminar;
    private javax.swing.JButton btnUsuario;
    private javax.swing.JLabel labelAlbumes;
    private javax.swing.JLabel labelArtistas;
    private javax.swing.JLabel labelCanciones;
    private javax.swing.JLabel labelDuracion;
    private javax.swing.JLabel labelMusicio1;
    private javax.swing.JLabel labelNombreCancin;
    private javax.swing.JLabel labelUsuario;
    private javax.swing.JPanel panelFondo2;
    private javax.swing.JPanel panelVerde2;
    private javax.swing.JLabel textoAgregarCancion;
    private javax.swing.JTextField txtDuracion;
    private javax.swing.JTextField txtNombreCancion;
    // End of variables declaration//GEN-END:variables
}
