/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sistemamusicapresentacion.albumes;

import sistemamusica.dtos.UsuarioDTO;
import sistemamusicadominio.Genero;
import sistemamusicapresentacion.main.ControladorUniversal;

/**
 *
 * @author gael_
 */
public class frmAgregarAlbum extends javax.swing.JFrame {
    
    UsuarioDTO usuario;
    ControladorUniversal controlador;
    
    /**
     * Creates new form frmAgregarAlbum
     */
    public frmAgregarAlbum(ControladorUniversal controlador, UsuarioDTO usuario) {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Agregar Album");
        this.controlador=controlador;
        this.usuario=usuario;
        LlenarCBGenero();
    }
    
    public void LlenarCBGenero(){
        for(Genero tipo : Genero.values()){
                comboboxGenero.addItem(tipo.toString());
            }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelFondo2 = new javax.swing.JPanel();
        panelVerde2 = new javax.swing.JPanel();
        btnArtistas2 = new javax.swing.JButton();
        labelArtistas = new javax.swing.JLabel();
        labelAlbumes = new javax.swing.JLabel();
        btnAlbumes = new javax.swing.JButton();
        btnCanciones = new javax.swing.JButton();
        labelCanciones = new javax.swing.JLabel();
        labelUsuario = new javax.swing.JLabel();
        btnUsuario = new javax.swing.JButton();
        labelMusicio1 = new javax.swing.JLabel();
        labelRol = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        textoAgregarAlbum = new javax.swing.JLabel();
        comboboxGenero = new javax.swing.JComboBox<>();
        labelFotoSubir = new javax.swing.JLabel();
        labelNombre = new javax.swing.JLabel();
        btnFoto = new javax.swing.JButton();
        btnAgregarAlbumContinuar = new javax.swing.JButton();
        comboboxArtista = new javax.swing.JComboBox<>();
        labelContrasenia1 = new javax.swing.JLabel();
        labelFechaISalida = new javax.swing.JLabel();
        fechaLanzamiento = new com.github.lgooddatepicker.components.DatePicker();
        btnVolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(850, 550));

        panelFondo2.setBackground(new java.awt.Color(0, 0, 0));

        panelVerde2.setBackground(new java.awt.Color(30, 215, 96));

        btnArtistas2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BlackStar.png"))); // NOI18N
        btnArtistas2.setBackground(new java.awt.Color(30, 215, 96));
        btnArtistas2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnArtistas2ActionPerformed(evt);
            }
        });

        labelArtistas.setText("Artistas");
        labelArtistas.setFont(new java.awt.Font("Gotham Black", 0, 12)); // NOI18N

        labelAlbumes.setText("Albumes");
        labelAlbumes.setFont(new java.awt.Font("Gotham Black", 0, 12)); // NOI18N

        btnAlbumes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/musica.png"))); // NOI18N
        btnAlbumes.setBackground(new java.awt.Color(30, 215, 96));

        btnCanciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/disco.png"))); // NOI18N
        btnCanciones.setBackground(new java.awt.Color(30, 215, 96));
        btnCanciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancionesActionPerformed(evt);
            }
        });

        labelCanciones.setText("Canciones");
        labelCanciones.setFont(new java.awt.Font("Gotham Black", 0, 12)); // NOI18N

        labelUsuario.setText("Usuario");
        labelUsuario.setFont(new java.awt.Font("Gotham Black", 0, 12)); // NOI18N

        btnUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/usuario.png"))); // NOI18N
        btnUsuario.setBackground(new java.awt.Color(30, 215, 96));
        btnUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelVerde2Layout = new javax.swing.GroupLayout(panelVerde2);
        panelVerde2.setLayout(panelVerde2Layout);
        panelVerde2Layout.setHorizontalGroup(
            panelVerde2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelVerde2Layout.createSequentialGroup()
                .addGroup(panelVerde2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelVerde2Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(panelVerde2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelCanciones)
                            .addGroup(panelVerde2Layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addGroup(panelVerde2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelAlbumes)
                                    .addGroup(panelVerde2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(btnCanciones)
                                        .addComponent(btnAlbumes)
                                        .addComponent(btnArtistas2))
                                    .addComponent(labelArtistas)))))
                    .addGroup(panelVerde2Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(panelVerde2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelUsuario)
                            .addComponent(btnUsuario))))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        panelVerde2Layout.setVerticalGroup(
            panelVerde2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelVerde2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(btnArtistas2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelArtistas, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(btnAlbumes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelAlbumes, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCanciones)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelCanciones, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 166, Short.MAX_VALUE)
                .addComponent(btnUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );

        labelMusicio1.setText("Music.io");
        labelMusicio1.setFont(new java.awt.Font("Gotham Black", 1, 36)); // NOI18N
        labelMusicio1.setForeground(new java.awt.Color(30, 215, 96));

        labelRol.setText("artista:");
        labelRol.setFont(new java.awt.Font("Gotham Bold", 1, 14)); // NOI18N
        labelRol.setForeground(new java.awt.Color(30, 215, 96));

        textoAgregarAlbum.setText("Agregar Album");
        textoAgregarAlbum.setFont(new java.awt.Font("Gotham Black", 1, 36)); // NOI18N
        textoAgregarAlbum.setForeground(new java.awt.Color(30, 215, 96));

        comboboxGenero.setFont(new java.awt.Font("Gotham Black", 1, 14)); // NOI18N
        comboboxGenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboboxGeneroActionPerformed(evt);
            }
        });

        labelFotoSubir.setText("subir foto");
        labelFotoSubir.setFont(new java.awt.Font("Gotham Black", 1, 14)); // NOI18N
        labelFotoSubir.setForeground(new java.awt.Color(30, 215, 96));

        labelNombre.setText("nombre:");
        labelNombre.setFont(new java.awt.Font("Gotham Bold", 1, 14)); // NOI18N
        labelNombre.setForeground(new java.awt.Color(30, 215, 96));

        btnFoto.setText("boton para subir foto");
        btnFoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFotoActionPerformed(evt);
            }
        });

        btnAgregarAlbumContinuar.setText("Guardar Album y Añadir Canciones");
        btnAgregarAlbumContinuar.setBackground(new java.awt.Color(30, 215, 96));
        btnAgregarAlbumContinuar.setFont(new java.awt.Font("Gotham Black", 1, 18)); // NOI18N
        btnAgregarAlbumContinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarAlbumContinuarActionPerformed(evt);
            }
        });

        comboboxArtista.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboboxArtista.setFont(new java.awt.Font("Gotham Black", 1, 14)); // NOI18N
        comboboxArtista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboboxArtistaActionPerformed(evt);
            }
        });

        labelContrasenia1.setText("genero:");
        labelContrasenia1.setFont(new java.awt.Font("Gotham Bold", 1, 14)); // NOI18N
        labelContrasenia1.setForeground(new java.awt.Color(30, 215, 96));

        labelFechaISalida.setText("fecha de salida:");
        labelFechaISalida.setFont(new java.awt.Font("Gotham Bold", 1, 14)); // NOI18N
        labelFechaISalida.setForeground(new java.awt.Color(30, 215, 96));

        btnVolver.setText("Volver");
        btnVolver.setBackground(new java.awt.Color(30, 215, 96));
        btnVolver.setFont(new java.awt.Font("Gotham Black", 1, 18)); // NOI18N
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelFondo2Layout = new javax.swing.GroupLayout(panelFondo2);
        panelFondo2.setLayout(panelFondo2Layout);
        panelFondo2Layout.setHorizontalGroup(
            panelFondo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFondo2Layout.createSequentialGroup()
                .addComponent(panelVerde2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(panelFondo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFondo2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 114, Short.MAX_VALUE)
                        .addComponent(textoAgregarAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(labelMusicio1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24))
                    .addGroup(panelFondo2Layout.createSequentialGroup()
                        .addGroup(panelFondo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelFondo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(panelFondo2Layout.createSequentialGroup()
                                    .addGroup(panelFondo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(panelFondo2Layout.createSequentialGroup()
                                            .addGap(289, 289, 289)
                                            .addComponent(labelFotoSubir))
                                        .addGroup(panelFondo2Layout.createSequentialGroup()
                                            .addGap(254, 254, 254)
                                            .addComponent(btnFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGap(38, 38, 38))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFondo2Layout.createSequentialGroup()
                                    .addGap(224, 224, 224)
                                    .addGroup(panelFondo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(comboboxGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(labelNombre)
                                        .addComponent(labelContrasenia1)
                                        .addComponent(labelRol)
                                        .addComponent(labelFechaISalida)
                                        .addGroup(panelFondo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(fechaLanzamiento, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(comboboxArtista, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(panelFondo2Layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(btnVolver)
                                .addGap(40, 40, 40)
                                .addComponent(btnAgregarAlbumContinuar)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        panelFondo2Layout.setVerticalGroup(
            panelFondo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelVerde2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelFondo2Layout.createSequentialGroup()
                .addGroup(panelFondo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelMusicio1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textoAgregarAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addComponent(labelNombre)
                .addGap(3, 3, 3)
                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelContrasenia1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboboxGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelRol)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboboxArtista, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelFechaISalida)
                .addGap(13, 13, 13)
                .addComponent(fechaLanzamiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(labelFotoSubir, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnFoto)
                .addGap(31, 31, 31)
                .addGroup(panelFondo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnVolver)
                    .addComponent(btnAgregarAlbumContinuar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFondo2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFondo2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnArtistas2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnArtistas2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnArtistas2ActionPerformed

    private void btnCancionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancionesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancionesActionPerformed

    private void btnUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUsuarioActionPerformed

    private void comboboxGeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboboxGeneroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboboxGeneroActionPerformed

    private void btnFotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFotoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFotoActionPerformed

    private void btnAgregarAlbumContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarAlbumContinuarActionPerformed
        controlador.mostrarAlbumesPrincipal(usuario);
        this.dispose();
    }//GEN-LAST:event_btnAgregarAlbumContinuarActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        controlador.mostrarAlbumesPrincipal(usuario);
        this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void comboboxArtistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboboxArtistaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboboxArtistaActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarAlbumContinuar;
    private javax.swing.JButton btnAlbumes;
    private javax.swing.JButton btnArtistas2;
    private javax.swing.JButton btnCanciones;
    private javax.swing.JButton btnFoto;
    private javax.swing.JButton btnUsuario;
    private javax.swing.JButton btnVolver;
    private javax.swing.JComboBox<String> comboboxArtista;
    private javax.swing.JComboBox<String> comboboxGenero;
    private com.github.lgooddatepicker.components.DatePicker fechaLanzamiento;
    private javax.swing.JLabel labelAlbumes;
    private javax.swing.JLabel labelArtistas;
    private javax.swing.JLabel labelCanciones;
    private javax.swing.JLabel labelContrasenia1;
    private javax.swing.JLabel labelFechaISalida;
    private javax.swing.JLabel labelFotoSubir;
    private javax.swing.JLabel labelMusicio1;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JLabel labelRol;
    private javax.swing.JLabel labelUsuario;
    private javax.swing.JPanel panelFondo2;
    private javax.swing.JPanel panelVerde2;
    private javax.swing.JLabel textoAgregarAlbum;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
