/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sistemamusicapresentacion.artistas;

/**
 *
 * @author gael_
 */
public class frmAgregarBanda extends javax.swing.JFrame {

    /**
     * Creates new form frmAgregarBanda
     */
    public frmAgregarBanda() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Agregar Banda");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelFondo1 = new javax.swing.JPanel();
        panelVerde1 = new javax.swing.JPanel();
        btnArtistas1 = new javax.swing.JButton();
        labelArtistas = new javax.swing.JLabel();
        labelAlbumes = new javax.swing.JLabel();
        btnAlbumes = new javax.swing.JButton();
        btnCanciones = new javax.swing.JButton();
        labelCanciones = new javax.swing.JLabel();
        labelUsuario = new javax.swing.JLabel();
        btnUsuario = new javax.swing.JButton();
        labelMusicio1 = new javax.swing.JLabel();
        labelRol = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        labelAgregarSolista = new javax.swing.JLabel();
        comboboxGenero = new javax.swing.JComboBox<>();
        labelFotoSubir = new javax.swing.JLabel();
        labelNombre = new javax.swing.JLabel();
        btnFoto = new javax.swing.JButton();
        btnRegistrarArtista = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        btnAgregarMiembro = new javax.swing.JButton();
        labelNombre1 = new javax.swing.JLabel();
        txtNombreIntegrante = new javax.swing.JTextField();
        comboboxRol = new javax.swing.JComboBox<>();
        labelContrasenia1 = new javax.swing.JLabel();
        labelFechaIngreso = new javax.swing.JLabel();
        fechaIngreso = new com.github.lgooddatepicker.components.DatePicker();
        labelFechaISalida = new javax.swing.JLabel();
        fechaSalida = new com.github.lgooddatepicker.components.DatePicker();
        jCheckBox1 = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(850, 550));
        setPreferredSize(new java.awt.Dimension(850, 550));

        panelFondo1.setBackground(new java.awt.Color(0, 0, 0));

        panelVerde1.setBackground(new java.awt.Color(30, 215, 96));

        btnArtistas1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BlackStar.png"))); // NOI18N
        btnArtistas1.setBackground(new java.awt.Color(30, 215, 96));
        btnArtistas1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnArtistas1ActionPerformed(evt);
            }
        });

        labelArtistas.setText("Artistas");
        labelArtistas.setFont(new java.awt.Font("Gotham Black", 0, 12)); // NOI18N

        labelAlbumes.setText("Albumes");
        labelAlbumes.setFont(new java.awt.Font("Gotham Black", 0, 12)); // NOI18N

        btnAlbumes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/musica.png"))); // NOI18N
        btnAlbumes.setBackground(new java.awt.Color(30, 215, 96));

        btnCanciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/disco.png"))); // NOI18N
        btnCanciones.setBackground(new java.awt.Color(30, 215, 96));
        btnCanciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancionesActionPerformed(evt);
            }
        });

        labelCanciones.setText("Canciones");
        labelCanciones.setFont(new java.awt.Font("Gotham Black", 0, 12)); // NOI18N

        labelUsuario.setText("Usuario");
        labelUsuario.setFont(new java.awt.Font("Gotham Black", 0, 12)); // NOI18N

        btnUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/usuario.png"))); // NOI18N
        btnUsuario.setBackground(new java.awt.Color(30, 215, 96));
        btnUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelVerde1Layout = new javax.swing.GroupLayout(panelVerde1);
        panelVerde1.setLayout(panelVerde1Layout);
        panelVerde1Layout.setHorizontalGroup(
            panelVerde1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelVerde1Layout.createSequentialGroup()
                .addGroup(panelVerde1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelVerde1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(panelVerde1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelCanciones)
                            .addGroup(panelVerde1Layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addGroup(panelVerde1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelAlbumes)
                                    .addGroup(panelVerde1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(btnCanciones)
                                        .addComponent(btnAlbumes)
                                        .addComponent(btnArtistas1))
                                    .addComponent(labelArtistas)))))
                    .addGroup(panelVerde1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(panelVerde1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelUsuario)
                            .addComponent(btnUsuario))))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        panelVerde1Layout.setVerticalGroup(
            panelVerde1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelVerde1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(btnArtistas1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelArtistas, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(btnAlbumes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelAlbumes, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCanciones)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelCanciones, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );

        labelMusicio1.setText("Music.io");
        labelMusicio1.setFont(new java.awt.Font("Gotham Black", 1, 36)); // NOI18N
        labelMusicio1.setForeground(new java.awt.Color(30, 215, 96));

        labelRol.setText("rol:");
        labelRol.setFont(new java.awt.Font("Gotham Bold", 1, 14)); // NOI18N
        labelRol.setForeground(new java.awt.Color(30, 215, 96));

        labelAgregarSolista.setText("Agregar Banda");
        labelAgregarSolista.setFont(new java.awt.Font("Gotham Black", 1, 36)); // NOI18N
        labelAgregarSolista.setForeground(new java.awt.Color(30, 215, 96));

        comboboxGenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboboxGenero.setFont(new java.awt.Font("Gotham Black", 1, 14)); // NOI18N
        comboboxGenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboboxGeneroActionPerformed(evt);
            }
        });

        labelFotoSubir.setText("subir foto");
        labelFotoSubir.setFont(new java.awt.Font("Gotham Black", 1, 14)); // NOI18N
        labelFotoSubir.setForeground(new java.awt.Color(30, 215, 96));

        labelNombre.setText("nombre de la banda:");
        labelNombre.setFont(new java.awt.Font("Gotham Bold", 1, 14)); // NOI18N
        labelNombre.setForeground(new java.awt.Color(30, 215, 96));

        btnFoto.setText("boton para subir foto");
        btnFoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFotoActionPerformed(evt);
            }
        });

        btnRegistrarArtista.setText("Guardar Artista");
        btnRegistrarArtista.setBackground(new java.awt.Color(30, 215, 96));
        btnRegistrarArtista.setFont(new java.awt.Font("Gotham Black", 1, 18)); // NOI18N
        btnRegistrarArtista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarArtistaActionPerformed(evt);
            }
        });

        btnVolver.setText("Volver");
        btnVolver.setBackground(new java.awt.Color(30, 215, 96));
        btnVolver.setFont(new java.awt.Font("Gotham Black", 1, 18)); // NOI18N
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        btnAgregarMiembro.setText("Agregar Miembro");
        btnAgregarMiembro.setBackground(new java.awt.Color(30, 215, 96));
        btnAgregarMiembro.setFont(new java.awt.Font("Gotham Black", 1, 18)); // NOI18N
        btnAgregarMiembro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarMiembroActionPerformed(evt);
            }
        });

        labelNombre1.setText("nombre del integrante:");
        labelNombre1.setFont(new java.awt.Font("Gotham Bold", 1, 14)); // NOI18N
        labelNombre1.setForeground(new java.awt.Color(30, 215, 96));

        comboboxRol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboboxRol.setFont(new java.awt.Font("Gotham Black", 1, 12)); // NOI18N
        comboboxRol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboboxRolActionPerformed(evt);
            }
        });

        labelContrasenia1.setText("genero:");
        labelContrasenia1.setFont(new java.awt.Font("Gotham Bold", 1, 14)); // NOI18N
        labelContrasenia1.setForeground(new java.awt.Color(30, 215, 96));

        labelFechaIngreso.setText("fecha de ingreso:");
        labelFechaIngreso.setFont(new java.awt.Font("Gotham Bold", 1, 14)); // NOI18N
        labelFechaIngreso.setForeground(new java.awt.Color(30, 215, 96));

        labelFechaISalida.setText("fecha de salida:");
        labelFechaISalida.setFont(new java.awt.Font("Gotham Bold", 1, 14)); // NOI18N
        labelFechaISalida.setForeground(new java.awt.Color(30, 215, 96));

        jCheckBox1.setText("Miembro Activo?");
        jCheckBox1.setBackground(new java.awt.Color(0, 0, 0));
        jCheckBox1.setFont(new java.awt.Font("Gotham Black", 0, 12)); // NOI18N
        jCheckBox1.setForeground(new java.awt.Color(30, 215, 96));

        javax.swing.GroupLayout panelFondo1Layout = new javax.swing.GroupLayout(panelFondo1);
        panelFondo1.setLayout(panelFondo1Layout);
        panelFondo1Layout.setHorizontalGroup(
            panelFondo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFondo1Layout.createSequentialGroup()
                .addComponent(panelVerde1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(panelFondo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelFondo1Layout.createSequentialGroup()
                        .addGroup(panelFondo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelFondo1Layout.createSequentialGroup()
                                .addGap(56, 56, 56)
                                .addGroup(panelFondo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(comboboxGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelNombre)
                                    .addComponent(labelContrasenia1)))
                            .addGroup(panelFondo1Layout.createSequentialGroup()
                                .addGap(120, 120, 120)
                                .addComponent(labelFotoSubir)))
                        .addGroup(panelFondo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelFondo1Layout.createSequentialGroup()
                                .addGap(124, 124, 124)
                                .addGroup(panelFondo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelNombre1)
                                    .addComponent(txtNombreIntegrante, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(comboboxRol, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelRol))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(panelFondo1Layout.createSequentialGroup()
                                .addGap(0, 90, Short.MAX_VALUE)
                                .addComponent(labelFechaIngreso)
                                .addGap(97, 97, 97)
                                .addComponent(labelFechaISalida)
                                .addGap(62, 62, 62))))
                    .addGroup(panelFondo1Layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addGroup(panelFondo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFondo1Layout.createSequentialGroup()
                                .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(panelFondo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnRegistrarArtista, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnAgregarMiembro, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(93, 93, 93))
                            .addGroup(panelFondo1Layout.createSequentialGroup()
                                .addComponent(btnFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jCheckBox1)
                                .addGap(141, 141, 141))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFondo1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panelFondo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFondo1Layout.createSequentialGroup()
                                .addComponent(fechaIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(234, 234, 234))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFondo1Layout.createSequentialGroup()
                                .addGroup(panelFondo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(fechaSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(panelFondo1Layout.createSequentialGroup()
                                        .addComponent(labelAgregarSolista, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(labelMusicio1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(24, 24, 24))))))
        );
        panelFondo1Layout.setVerticalGroup(
            panelFondo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelVerde1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelFondo1Layout.createSequentialGroup()
                .addGroup(panelFondo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelMusicio1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelFondo1Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(labelAgregarSolista, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addGroup(panelFondo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelNombre)
                            .addComponent(labelNombre1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelFondo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNombreIntegrante, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(panelFondo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelRol)
                            .addComponent(labelContrasenia1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelFondo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comboboxGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboboxRol, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(panelFondo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelFotoSubir)
                            .addComponent(labelFechaIngreso)
                            .addComponent(labelFechaISalida))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelFondo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fechaIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fechaSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(panelFondo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelFondo1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(btnFoto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnVolver)
                        .addGap(41, 41, 41))
                    .addGroup(panelFondo1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jCheckBox1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                        .addComponent(btnAgregarMiembro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnRegistrarArtista)
                        .addGap(23, 23, 23))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFondo1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelFondo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnArtistas1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnArtistas1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnArtistas1ActionPerformed

    private void btnCancionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancionesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancionesActionPerformed

    private void comboboxGeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboboxGeneroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboboxGeneroActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnRegistrarArtistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarArtistaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegistrarArtistaActionPerformed

    private void btnFotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFotoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFotoActionPerformed

    private void btnAgregarMiembroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarMiembroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgregarMiembroActionPerformed

    private void btnUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUsuarioActionPerformed

    private void comboboxRolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboboxRolActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboboxRolActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarMiembro;
    private javax.swing.JButton btnAlbumes;
    private javax.swing.JButton btnArtistas1;
    private javax.swing.JButton btnCanciones;
    private javax.swing.JButton btnFoto;
    private javax.swing.JButton btnRegistrarArtista;
    private javax.swing.JButton btnUsuario;
    private javax.swing.JButton btnVolver;
    private javax.swing.JComboBox<String> comboboxGenero;
    private javax.swing.JComboBox<String> comboboxRol;
    private com.github.lgooddatepicker.components.DatePicker fechaIngreso;
    private com.github.lgooddatepicker.components.DatePicker fechaSalida;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel labelAgregarSolista;
    private javax.swing.JLabel labelAlbumes;
    private javax.swing.JLabel labelArtistas;
    private javax.swing.JLabel labelCanciones;
    private javax.swing.JLabel labelContrasenia1;
    private javax.swing.JLabel labelFechaISalida;
    private javax.swing.JLabel labelFechaIngreso;
    private javax.swing.JLabel labelFotoSubir;
    private javax.swing.JLabel labelMusicio1;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JLabel labelNombre1;
    private javax.swing.JLabel labelRol;
    private javax.swing.JLabel labelUsuario;
    private javax.swing.JPanel panelFondo1;
    private javax.swing.JPanel panelVerde1;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNombreIntegrante;
    // End of variables declaration//GEN-END:variables
}
