/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sistemamusicapresentacion.main;

import javax.swing.JOptionPane;
import sistemamusicanegocio.exception.NegocioException;
import sistemamusicanegocio.fabrica.FabricaObjetosNegocio;
import sistemamusicanegocio.interfaces.IUsuariosBO;

/**
 *
 * @author gael_
 */
public class frmIniciarSesion extends javax.swing.JFrame {

    private final IUsuariosBO usuarioBO = FabricaObjetosNegocio.crearUsuariosBO();
    private final ControladorUniversal control;

    /**
     * Creates new form frmIniciarSesion
     *
     * @param control Clase control
     */
    public frmIniciarSesion(ControladorUniversal control) {
        initComponents();
        this.control = control;
        setLocationRelativeTo(null);
        setTitle("Iniciar Sesion");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelFondo = new javax.swing.JPanel();
        labelMusicio1 = new javax.swing.JLabel();
        labelIniciarSesion = new javax.swing.JLabel();
        labelContrasenia = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        labelUsername = new javax.swing.JLabel();
        btnAcceder = new javax.swing.JButton();
        btnRegistrarse1 = new javax.swing.JButton();
        txtContrasenia = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(850, 550));

        panelFondo.setBackground(new java.awt.Color(0, 0, 0));

        labelMusicio1.setFont(new java.awt.Font("Gotham Black", 1, 36)); // NOI18N
        labelMusicio1.setForeground(new java.awt.Color(30, 215, 96));
        labelMusicio1.setText("Music.io");

        labelIniciarSesion.setFont(new java.awt.Font("Gotham Black", 1, 36)); // NOI18N
        labelIniciarSesion.setForeground(new java.awt.Color(30, 215, 96));
        labelIniciarSesion.setText("Iniciar Sesion");

        labelContrasenia.setFont(new java.awt.Font("Gotham Bold", 1, 14)); // NOI18N
        labelContrasenia.setForeground(new java.awt.Color(30, 215, 96));
        labelContrasenia.setText("contraseña:");

        labelUsername.setFont(new java.awt.Font("Gotham Bold", 1, 14)); // NOI18N
        labelUsername.setForeground(new java.awt.Color(30, 215, 96));
        labelUsername.setText("username:");

        btnAcceder.setBackground(new java.awt.Color(30, 215, 96));
        btnAcceder.setFont(new java.awt.Font("Gotham Black", 1, 18)); // NOI18N
        btnAcceder.setText("Acceder");
        btnAcceder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAccederActionPerformed(evt);
            }
        });

        btnRegistrarse1.setBackground(new java.awt.Color(30, 215, 96));
        btnRegistrarse1.setFont(new java.awt.Font("Gotham Black", 1, 18)); // NOI18N
        btnRegistrarse1.setText("Registrarse");
        btnRegistrarse1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarse1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelFondoLayout = new javax.swing.GroupLayout(panelFondo);
        panelFondo.setLayout(panelFondoLayout);
        panelFondoLayout.setHorizontalGroup(
            panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFondoLayout.createSequentialGroup()
                .addContainerGap(317, Short.MAX_VALUE)
                .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFondoLayout.createSequentialGroup()
                        .addComponent(labelMusicio1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(135, 135, 135))
                    .addComponent(labelIniciarSesion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFondoLayout.createSequentialGroup()
                        .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(labelContrasenia)
                            .addComponent(txtUsername, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                            .addComponent(labelUsername)
                            .addComponent(txtContrasenia))
                        .addGap(138, 138, 138))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFondoLayout.createSequentialGroup()
                        .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnRegistrarse1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAcceder, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(180, 180, 180)))
                .addGap(152, 152, 152))
        );
        panelFondoLayout.setVerticalGroup(
            panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFondoLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(labelMusicio1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelIniciarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(labelUsername)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labelContrasenia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtContrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(btnAcceder)
                .addGap(18, 18, 18)
                .addComponent(btnRegistrarse1)
                .addContainerGap(111, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFondo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAccederActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAccederActionPerformed

        String username = txtUsername.getText();
        char[] contraseniaChars = txtContrasenia.getPassword();
        String contrasenia = new String(contraseniaChars);

        System.out.println(contrasenia);

        try {
            usuarioBO.iniciarSesion(username, contrasenia); // Hacer que este metodo busque si existe una cuenta con el mismo username
            JOptionPane.showMessageDialog(this, "El usuario: " + username
                    + " ha iniciado sesion", "Info.",
                    JOptionPane.INFORMATION_MESSAGE); // TODO: Eliminar cuando exista pantalla principal
        } catch (NegocioException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Info.",
                    JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnAccederActionPerformed

    private void btnRegistrarse1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarse1ActionPerformed

        control.mostrarModuloRegistrarUsuario();
        this.dispose();

    }//GEN-LAST:event_btnRegistrarse1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAcceder;
    private javax.swing.JButton btnRegistrarse1;
    private javax.swing.JLabel labelContrasenia;
    private javax.swing.JLabel labelIniciarSesion;
    private javax.swing.JLabel labelMusicio1;
    private javax.swing.JLabel labelUsername;
    private javax.swing.JPanel panelFondo;
    private javax.swing.JPasswordField txtContrasenia;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
